### ISSUE TITLE
helm-selection background color

### ISSUE THREAD

**Issue by rcdeoliveira** [ianpan870102/tron-legacy-emacs-theme#4]
I am using spacemacs with helm. On helm selections, the active item background goes green which it doesn't have enough contrast with font color, to solve this the theme could add:

 `(helm-selection ((t (:background "gray18" :distant-foreground "black"))))

**Comment by ianpan870102** [comment]
I just performed a huge refactor of the code and provided support for magit/helm/ivy etc. Feel free to try it now :-)
Please reopen if you feel there's something missing

**Comment by gugl** [comment]
I have a similar problem. I can hardly spot a contrast for the selected line in helm. Using the version 20210420.1201
Do I miss something obvious?
![helm selection tron legacy emacs theme](https://user-images.githubusercontent.com/453478/122082131-04283d80-ce00-11eb-88d5-92a5fa76d47f.png)
