### ISSUE TITLE
org-done face is very difficult to read

### ISSUE THREAD

**Issue by lhernanz** [ianpan870102/tron-legacy-emacs-theme#8]
I have just started used your theme and I love it! I have only one minor issue with it and it is that the org-done face it is really difficult to read. I completely understand that the whole purpose of that face is not to distract you but, if you have multiple done states, it is useful to be able to read them and with the current color options, this is really difficult to do. Can you have a look to see if you can improve a little bit the readability of that face?
Thanks

**Comment by ianpan870102** [comment]
Hi! Thanks for the feedback, I'll see what I can do about it

**Comment by ianpan870102** [comment]
I've made the following changes:

```emacs-lisp
  `(org-todo ((,class (:box (:line-width 1 :color ,tron-lightred)
                       :foreground ,tron-lightred))))
  `(org-done ((,class (:box (:line-width 1 :color ,tron-lightgreen)
                       :foreground ,tron-lightgreen))))
```

![image](https://user-images.githubusercontent.com/36686900/83372526-1d7a6980-a3f8-11ea-8744-09a346452a29.png)

Btw, tron-legacy-theme is now on MELPA! I suggest you pull changes from there and also enjoy future updates :-) Glad you like my theme

**Comment by lhernanz** [comment]
It works! Thank you very much. I am using the MELPA version now.
